/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'beeProducts' : IDL.Null,
  'rawHoney' : IDL.Null,
  'naturalHoney' : IDL.Null,
});
export const Price = IDL.Record({
  'salePrice' : IDL.Opt(IDL.Float64),
  'listPrice' : IDL.Float64,
});
export const AvailabilityStatus = IDL.Variant({
  'inStock' : IDL.Null,
  'outOfStock' : IDL.Null,
  'limited' : IDL.Null,
});
export const WeightVariant = IDL.Record({
  'weight' : IDL.Nat,
  'description' : IDL.Text,
  'price' : Price,
});
export const FlavorVariant = IDL.Record({
  'weight' : IDL.Nat,
  'flavor' : IDL.Text,
  'description' : IDL.Text,
  'price' : Price,
});
export const ProductVariants = IDL.Variant({
  'weight' : IDL.Vec(WeightVariant),
  'flavor' : IDL.Vec(FlavorVariant),
});
export const ProductUpdateType = IDL.Variant({
  'seasonalAvailability' : IDL.Null,
  'priceUpdate' : IDL.Null,
  'newHarvest' : IDL.Null,
  'limitedTimeOffer' : IDL.Null,
});
export const Time = IDL.Int;
export const ProductUpdate = IDL.Record({
  'id' : IDL.Nat,
  'productUpdateType' : ProductUpdateType,
  'productId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'created' : Time,
  'isDeleted' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Opt(ProductVariants),
  'availability' : AvailabilityStatus,
  'stock' : IDL.Nat,
  'timestamp' : Time,
  'category' : Category,
  'image' : IDL.Text,
  'price' : Price,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactFormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Logo = IDL.Record({
  'data' : IDL.Vec(IDL.Nat8),
  'mimeType' : IDL.Text,
});
export const SeedProductsResult = IDL.Variant({
  'seeded' : IDL.Record({ 'count' : IDL.Nat }),
  'alreadySeeded' : IDL.Null,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Category,
        Price,
        IDL.Text,
        AvailabilityStatus,
        IDL.Opt(ProductVariants),
        IDL.Nat,
      ],
      [IDL.Nat],
      [],
    ),
  'createProductUpdate' : IDL.Func(
      [ProductUpdateType, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteProductUpdate' : IDL.Func([IDL.Nat], [], []),
  'getAllProductUpdates' : IDL.Func([], [IDL.Vec(ProductUpdate)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getLimitedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getLogo' : IDL.Func([], [IDL.Opt(Logo)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductUpdatesByProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductUpdate)],
      ['query'],
    ),
  'getProductUpdatesByType' : IDL.Func(
      [ProductUpdateType],
      [IDL.Vec(ProductUpdate)],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'makeMeAdmin' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedProducts' : IDL.Func([], [SeedProductsResult], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateLogo' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Category,
        Price,
        IDL.Text,
        AvailabilityStatus,
        IDL.Opt(ProductVariants),
        IDL.Nat,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'beeProducts' : IDL.Null,
    'rawHoney' : IDL.Null,
    'naturalHoney' : IDL.Null,
  });
  const Price = IDL.Record({
    'salePrice' : IDL.Opt(IDL.Float64),
    'listPrice' : IDL.Float64,
  });
  const AvailabilityStatus = IDL.Variant({
    'inStock' : IDL.Null,
    'outOfStock' : IDL.Null,
    'limited' : IDL.Null,
  });
  const WeightVariant = IDL.Record({
    'weight' : IDL.Nat,
    'description' : IDL.Text,
    'price' : Price,
  });
  const FlavorVariant = IDL.Record({
    'weight' : IDL.Nat,
    'flavor' : IDL.Text,
    'description' : IDL.Text,
    'price' : Price,
  });
  const ProductVariants = IDL.Variant({
    'weight' : IDL.Vec(WeightVariant),
    'flavor' : IDL.Vec(FlavorVariant),
  });
  const ProductUpdateType = IDL.Variant({
    'seasonalAvailability' : IDL.Null,
    'priceUpdate' : IDL.Null,
    'newHarvest' : IDL.Null,
    'limitedTimeOffer' : IDL.Null,
  });
  const Time = IDL.Int;
  const ProductUpdate = IDL.Record({
    'id' : IDL.Nat,
    'productUpdateType' : ProductUpdateType,
    'productId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'created' : Time,
    'isDeleted' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Opt(ProductVariants),
    'availability' : AvailabilityStatus,
    'stock' : IDL.Nat,
    'timestamp' : Time,
    'category' : Category,
    'image' : IDL.Text,
    'price' : Price,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactFormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Logo = IDL.Record({
    'data' : IDL.Vec(IDL.Nat8),
    'mimeType' : IDL.Text,
  });
  const SeedProductsResult = IDL.Variant({
    'seeded' : IDL.Record({ 'count' : IDL.Nat }),
    'alreadySeeded' : IDL.Null,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          Price,
          IDL.Text,
          AvailabilityStatus,
          IDL.Opt(ProductVariants),
          IDL.Nat,
        ],
        [IDL.Nat],
        [],
      ),
    'createProductUpdate' : IDL.Func(
        [ProductUpdateType, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteProductUpdate' : IDL.Func([IDL.Nat], [], []),
    'getAllProductUpdates' : IDL.Func([], [IDL.Vec(ProductUpdate)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getLimitedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getLogo' : IDL.Func([], [IDL.Opt(Logo)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductUpdatesByProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductUpdate)],
        ['query'],
      ),
    'getProductUpdatesByType' : IDL.Func(
        [ProductUpdateType],
        [IDL.Vec(ProductUpdate)],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'makeMeAdmin' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedProducts' : IDL.Func([], [SeedProductsResult], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateLogo' : IDL.Func([IDL.Text, IDL.Vec(IDL.Nat8)], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Category,
          Price,
          IDL.Text,
          AvailabilityStatus,
          IDL.Opt(ProductVariants),
          IDL.Nat,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };