/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AvailabilityStatus = { 'inStock' : null } |
  { 'outOfStock' : null } |
  { 'limited' : null };
export type Category = { 'beeProducts' : null } |
  { 'rawHoney' : null } |
  { 'naturalHoney' : null };
export interface ContactFormSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface CreateProductPayload {
  'name' : string,
  'description' : string,
  'variants' : [] | [ProductVariants],
  'availability' : AvailabilityStatus,
  'stock' : bigint,
  'category' : Category,
  'image' : string,
  'price' : Price,
}
export type CustomerIdentifier = { 'email' : string } |
  { 'phone' : string };
export interface DeliveryAddress {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'name' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'phoneNumber' : string,
}
export interface FlavorVariant {
  'weight' : bigint,
  'flavor' : string,
  'description' : string,
  'price' : Price,
}
export interface Logo { 'data' : Uint8Array, 'mimeType' : string }
export interface OrderItem {
  'productId' : bigint,
  'flavorVariant' : [] | [FlavorVariant],
  'quantity' : bigint,
  'weightVariant' : [] | [WeightVariant],
}
export type OrderStatus = { 'pending' : null } |
  { 'transit' : null } |
  { 'delivered' : null } |
  { 'inProgress' : null };
export interface OrderType {
  'id' : bigint,
  'status' : OrderStatus,
  'customerIdentifier' : CustomerIdentifier,
  'createdAt' : Time,
  'updatedAt' : Time,
  'address' : DeliveryAddress,
  'items' : Array<OrderItem>,
  'totalPrice' : number,
}
export interface Price { 'salePrice' : [] | [number], 'listPrice' : number }
export interface Product {
  'id' : bigint,
  'created' : Time,
  'isDeleted' : boolean,
  'name' : string,
  'description' : string,
  'variants' : [] | [ProductVariants],
  'availability' : AvailabilityStatus,
  'stock' : bigint,
  'timestamp' : Time,
  'category' : Category,
  'image' : string,
  'price' : Price,
}
export interface ProductUpdate {
  'id' : bigint,
  'productUpdateType' : ProductUpdateType,
  'productId' : bigint,
  'message' : string,
  'timestamp' : Time,
}
export type ProductUpdateType = { 'seasonalAvailability' : null } |
  { 'priceUpdate' : null } |
  { 'newHarvest' : null } |
  { 'limitedTimeOffer' : null };
export type ProductVariants = { 'weight' : Array<WeightVariant> } |
  { 'flavor' : Array<FlavorVariant> };
export interface StoreSettings {
  'certificationsContent' : string,
  'backgroundImage' : [] | [string],
  'mapUrl' : string,
  'aboutContent' : string,
  'certificationsImage' : [] | [string],
  'contactDetails' : string,
}
export type Time = bigint;
export interface UpdateProductPayload {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'variants' : [] | [ProductVariants],
  'availability' : AvailabilityStatus,
  'stock' : bigint,
  'category' : Category,
  'image' : string,
  'price' : Price,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightVariant {
  'weight' : bigint,
  'description' : string,
  'price' : Price,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminLogin' : ActorMethod<
    [string, string],
    { 'error' : string } |
      { 'success' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<
    [string, Array<OrderItem>, number, DeliveryAddress],
    { 'success' : bigint }
  >,
  'createProduct' : ActorMethod<
    [CreateProductPayload],
    { 'error' : string } |
      { 'success' : Product }
  >,
  'createProductUpdate' : ActorMethod<
    [ProductUpdateType, bigint, string],
    bigint
  >,
  'deleteCustomerAddress' : ActorMethod<[string, bigint], undefined>,
  'deleteProduct' : ActorMethod<
    [bigint],
    { 'error' : string } |
      { 'success' : null }
  >,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getAllOrders' : ActorMethod<[], Array<OrderType>>,
  'getAllProductUpdates' : ActorMethod<[], Array<ProductUpdate>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCustomerAddresses' : ActorMethod<[string], Array<DeliveryAddress>>,
  'getCustomerOrders' : ActorMethod<[string], Array<OrderType>>,
  'getLogo' : ActorMethod<[], [] | [Logo]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductUpdatesByProduct' : ActorMethod<[bigint], Array<ProductUpdate>>,
  'getProductUpdatesByType' : ActorMethod<
    [ProductUpdateType],
    Array<ProductUpdate>
  >,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getStoreSettings' : ActorMethod<[], StoreSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdminSessionValid' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCustomerSessionValid' : ActorMethod<[string], boolean>,
  'loginCustomerByEmail' : ActorMethod<[string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCustomerAddress' : ActorMethod<[string, DeliveryAddress], undefined>,
  'setLogo' : ActorMethod<[Logo], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [UpdateProductPayload],
    { 'error' : string } |
      { 'success' : Product }
  >,
  'updateStoreSettings' : ActorMethod<[StoreSettings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];