/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AvailabilityStatus = { 'inStock' : null } |
  { 'outOfStock' : null } |
  { 'limited' : null };
export type Category = { 'beeProducts' : null } |
  { 'rawHoney' : null } |
  { 'naturalHoney' : null };
export interface ContactFormSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export type CustomerIdentifier = { 'email' : string } |
  { 'phone' : string };
export interface DeliveryAddress {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'name' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : string,
  'phoneNumber' : string,
}
export interface FlavorVariant {
  'weight' : bigint,
  'flavor' : string,
  'description' : string,
  'price' : Price,
}
export interface Logo { 'data' : Uint8Array, 'mimeType' : string }
export interface OrderItem {
  'productId' : bigint,
  'flavorVariant' : [] | [FlavorVariant],
  'quantity' : bigint,
  'weightVariant' : [] | [WeightVariant],
}
export type OrderStatus = { 'pending' : null } |
  { 'transit' : null } |
  { 'delivered' : null } |
  { 'inProgress' : null };
export interface OrderType {
  'id' : bigint,
  'status' : OrderStatus,
  'customerIdentifier' : CustomerIdentifier,
  'createdAt' : Time,
  'updatedAt' : Time,
  'address' : DeliveryAddress,
  'items' : Array<OrderItem>,
  'totalPrice' : number,
}
export interface Price { 'salePrice' : [] | [number], 'listPrice' : number }
export interface Product {
  'id' : bigint,
  'created' : Time,
  'isDeleted' : boolean,
  'name' : string,
  'description' : string,
  'variants' : [] | [ProductVariants],
  'availability' : AvailabilityStatus,
  'stock' : bigint,
  'timestamp' : Time,
  'category' : Category,
  'image' : string,
  'price' : Price,
}
export interface ProductUpdate {
  'id' : bigint,
  'productUpdateType' : ProductUpdateType,
  'productId' : bigint,
  'message' : string,
  'timestamp' : Time,
}
export type ProductUpdateType = { 'seasonalAvailability' : null } |
  { 'priceUpdate' : null } |
  { 'newHarvest' : null } |
  { 'limitedTimeOffer' : null };
export type ProductVariants = { 'weight' : Array<WeightVariant> } |
  { 'flavor' : Array<FlavorVariant> };
export type SeedProductsResult = { 'seeded' : { 'count' : bigint } } |
  { 'alreadySeeded' : null };
export interface SiteSettings {
  'certificationsContent' : string,
  'backgroundImage' : [] | [string],
  'mapUrl' : string,
  'aboutContent' : string,
  'certificationsImage' : [] | [string],
  'contactDetails' : string,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeightVariant {
  'weight' : bigint,
  'description' : string,
  'price' : Price,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdmin' : ActorMethod<[Principal], undefined>,
  'adminLogin' : ActorMethod<[string, string], [] | [string]>,
  'adminLogout' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrder' : ActorMethod<
    [string, Array<OrderItem>, number, DeliveryAddress],
    bigint
  >,
  'createProduct' : ActorMethod<
    [
      string,
      string,
      string,
      Category,
      Price,
      string,
      AvailabilityStatus,
      [] | [ProductVariants],
      bigint,
    ],
    bigint
  >,
  'createProductUpdate' : ActorMethod<
    [string, ProductUpdateType, bigint, string],
    bigint
  >,
  'customerLogin' : ActorMethod<[CustomerIdentifier], [] | [string]>,
  'customerLogout' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[string, bigint], undefined>,
  'deleteProductUpdate' : ActorMethod<[string, bigint], undefined>,
  'getAllOrders' : ActorMethod<[string], Array<OrderType>>,
  'getAllProductUpdates' : ActorMethod<[], Array<ProductUpdate>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllProductsAdmin' : ActorMethod<[string], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactFormSubmissions' : ActorMethod<
    [string],
    Array<ContactFormSubmission>
  >,
  'getCustomerOrders' : ActorMethod<[string], Array<OrderType>>,
  'getCustomerSessionInfo' : ActorMethod<[string], [] | [CustomerIdentifier]>,
  'getDeliveryAddress' : ActorMethod<[string], [] | [DeliveryAddress]>,
  'getLimitedProducts' : ActorMethod<[], Array<Product>>,
  'getLogo' : ActorMethod<[], [] | [Logo]>,
  'getOrder' : ActorMethod<[string, bigint], [] | [OrderType]>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductAdmin' : ActorMethod<[string, bigint], [] | [Product]>,
  'getProductUpdatesByProduct' : ActorMethod<[bigint], Array<ProductUpdate>>,
  'getProductUpdatesByType' : ActorMethod<
    [ProductUpdateType],
    Array<ProductUpdate>
  >,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getSiteSettings' : ActorMethod<[], SiteSettings>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'promoteToUser' : ActorMethod<[Principal], undefined>,
  'removeAdmin' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDeliveryAddress' : ActorMethod<[string, DeliveryAddress], undefined>,
  'seedProducts' : ActorMethod<[string], SeedProductsResult>,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
  'updateLogo' : ActorMethod<[string, string, Uint8Array], undefined>,
  'updateOrderStatus' : ActorMethod<[string, bigint, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      string,
      bigint,
      string,
      string,
      Category,
      Price,
      string,
      AvailabilityStatus,
      [] | [ProductVariants],
      bigint,
    ],
    undefined
  >,
  'updateSiteSettings' : ActorMethod<[string, SiteSettings], undefined>,
  'validateAdminSession' : ActorMethod<[string], boolean>,
  'validateCustomerSession' : ActorMethod<[string], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];