/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'organicWild' : IDL.Null,
  'rawForest' : IDL.Null,
  'herbalInfused' : IDL.Null,
  'honeyComb' : IDL.Null,
});
export const AvailabilityStatus = IDL.Variant({
  'inStock' : IDL.Null,
  'outOfStock' : IDL.Null,
  'limited' : IDL.Null,
});
export const ProductUpdateType = IDL.Variant({
  'seasonalAvailability' : IDL.Null,
  'priceUpdate' : IDL.Null,
  'newHarvest' : IDL.Null,
  'limitedTimeOffer' : IDL.Null,
});
export const Time = IDL.Int;
export const ProductUpdate = IDL.Record({
  'id' : IDL.Nat,
  'productUpdateType' : ProductUpdateType,
  'productId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'created' : Time,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'availability' : AvailabilityStatus,
  'timestamp' : Time,
  'category' : Category,
  'price' : IDL.Float64,
  'images' : IDL.Vec(IDL.Text),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ContactFormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Float64,
        IDL.Vec(IDL.Text),
        AvailabilityStatus,
      ],
      [IDL.Nat],
      [],
    ),
  'createProductUpdate' : IDL.Func(
      [ProductUpdateType, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'deleteProductUpdate' : IDL.Func([IDL.Nat], [], []),
  'getAllProductUpdates' : IDL.Func([], [IDL.Vec(ProductUpdate)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactFormSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductUpdatesByProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductUpdate)],
      ['query'],
    ),
  'getProductUpdatesByType' : IDL.Func(
      [ProductUpdateType],
      [IDL.Vec(ProductUpdate)],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        Category,
        IDL.Float64,
        IDL.Vec(IDL.Text),
        AvailabilityStatus,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'organicWild' : IDL.Null,
    'rawForest' : IDL.Null,
    'herbalInfused' : IDL.Null,
    'honeyComb' : IDL.Null,
  });
  const AvailabilityStatus = IDL.Variant({
    'inStock' : IDL.Null,
    'outOfStock' : IDL.Null,
    'limited' : IDL.Null,
  });
  const ProductUpdateType = IDL.Variant({
    'seasonalAvailability' : IDL.Null,
    'priceUpdate' : IDL.Null,
    'newHarvest' : IDL.Null,
    'limitedTimeOffer' : IDL.Null,
  });
  const Time = IDL.Int;
  const ProductUpdate = IDL.Record({
    'id' : IDL.Nat,
    'productUpdateType' : ProductUpdateType,
    'productId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'created' : Time,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'availability' : AvailabilityStatus,
    'timestamp' : Time,
    'category' : Category,
    'price' : IDL.Float64,
    'images' : IDL.Vec(IDL.Text),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ContactFormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Float64,
          IDL.Vec(IDL.Text),
          AvailabilityStatus,
        ],
        [IDL.Nat],
        [],
      ),
    'createProductUpdate' : IDL.Func(
        [ProductUpdateType, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'deleteProductUpdate' : IDL.Func([IDL.Nat], [], []),
    'getAllProductUpdates' : IDL.Func([], [IDL.Vec(ProductUpdate)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactFormSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductUpdatesByProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductUpdate)],
        ['query'],
      ),
    'getProductUpdatesByType' : IDL.Func(
        [ProductUpdateType],
        [IDL.Vec(ProductUpdate)],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          Category,
          IDL.Float64,
          IDL.Vec(IDL.Text),
          AvailabilityStatus,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };