/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AvailabilityStatus = { 'inStock' : null } |
  { 'outOfStock' : null } |
  { 'limited' : null };
export type Category = { 'organicWild' : null } |
  { 'rawForest' : null } |
  { 'herbalInfused' : null } |
  { 'honeyComb' : null };
export interface ContactFormSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
}
export interface Product {
  'id' : bigint,
  'created' : Time,
  'name' : string,
  'description' : string,
  'availability' : AvailabilityStatus,
  'timestamp' : Time,
  'category' : Category,
  'price' : number,
  'images' : Array<string>,
}
export interface ProductUpdate {
  'id' : bigint,
  'productUpdateType' : ProductUpdateType,
  'productId' : bigint,
  'message' : string,
  'timestamp' : Time,
}
export type ProductUpdateType = { 'seasonalAvailability' : null } |
  { 'priceUpdate' : null } |
  { 'newHarvest' : null } |
  { 'limitedTimeOffer' : null };
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createProduct' : ActorMethod<
    [string, string, Category, number, Array<string>, AvailabilityStatus],
    bigint
  >,
  'createProductUpdate' : ActorMethod<
    [ProductUpdateType, bigint, string],
    bigint
  >,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'deleteProductUpdate' : ActorMethod<[bigint], undefined>,
  'getAllProductUpdates' : ActorMethod<[], Array<ProductUpdate>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactFormSubmissions' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getProduct' : ActorMethod<[bigint], [] | [Product]>,
  'getProductUpdatesByProduct' : ActorMethod<[bigint], Array<ProductUpdate>>,
  'getProductUpdatesByType' : ActorMethod<
    [ProductUpdateType],
    Array<ProductUpdate>
  >,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], bigint>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      Category,
      number,
      Array<string>,
      AvailabilityStatus,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];