/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Price = IDL.Record({
  'salePrice' : IDL.Opt(IDL.Float64),
  'listPrice' : IDL.Float64,
});
export const FlavorVariant = IDL.Record({
  'weight' : IDL.Nat,
  'flavor' : IDL.Text,
  'description' : IDL.Text,
  'price' : Price,
});
export const WeightVariant = IDL.Record({
  'weight' : IDL.Nat,
  'description' : IDL.Text,
  'price' : Price,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'flavorVariant' : IDL.Opt(FlavorVariant),
  'quantity' : IDL.Nat,
  'weightVariant' : IDL.Opt(WeightVariant),
});
export const DeliveryAddress = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const ProductVariants = IDL.Variant({
  'weight' : IDL.Vec(WeightVariant),
  'flavor' : IDL.Vec(FlavorVariant),
});
export const AvailabilityStatus = IDL.Variant({
  'inStock' : IDL.Null,
  'outOfStock' : IDL.Null,
  'limited' : IDL.Null,
});
export const Category = IDL.Variant({
  'beeProducts' : IDL.Null,
  'rawHoney' : IDL.Null,
  'naturalHoney' : IDL.Null,
});
export const CreateProductPayload = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Opt(ProductVariants),
  'availability' : AvailabilityStatus,
  'stock' : IDL.Nat,
  'category' : Category,
  'image' : IDL.Text,
  'price' : Price,
});
export const Time = IDL.Int;
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'created' : Time,
  'isDeleted' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Opt(ProductVariants),
  'availability' : AvailabilityStatus,
  'stock' : IDL.Nat,
  'timestamp' : Time,
  'category' : Category,
  'image' : IDL.Text,
  'price' : Price,
});
export const ProductUpdateType = IDL.Variant({
  'seasonalAvailability' : IDL.Null,
  'priceUpdate' : IDL.Null,
  'newHarvest' : IDL.Null,
  'limitedTimeOffer' : IDL.Null,
});
export const ContactFormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'transit' : IDL.Null,
  'delivered' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const CustomerIdentifier = IDL.Variant({
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderType = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'customerIdentifier' : CustomerIdentifier,
  'createdAt' : Time,
  'updatedAt' : Time,
  'address' : DeliveryAddress,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Float64,
});
export const ProductUpdate = IDL.Record({
  'id' : IDL.Nat,
  'productUpdateType' : ProductUpdateType,
  'productId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Logo = IDL.Record({
  'data' : IDL.Vec(IDL.Nat8),
  'mimeType' : IDL.Text,
});
export const StoreSettings = IDL.Record({
  'certificationsContent' : IDL.Text,
  'backgroundImage' : IDL.Opt(IDL.Text),
  'mapUrl' : IDL.Text,
  'aboutContent' : IDL.Text,
  'certificationsImage' : IDL.Opt(IDL.Text),
  'contactDetails' : IDL.Text,
});
export const UpdateProductPayload = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'variants' : IDL.Opt(ProductVariants),
  'availability' : AvailabilityStatus,
  'stock' : IDL.Nat,
  'category' : Category,
  'image' : IDL.Text,
  'price' : Price,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminLogin' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'error' : IDL.Text, 'success' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrder' : IDL.Func(
      [IDL.Text, IDL.Vec(OrderItem), IDL.Float64, DeliveryAddress],
      [IDL.Variant({ 'success' : IDL.Nat })],
      [],
    ),
  'createProduct' : IDL.Func(
      [CreateProductPayload],
      [IDL.Variant({ 'error' : IDL.Text, 'success' : Product })],
      [],
    ),
  'createProductUpdate' : IDL.Func(
      [ProductUpdateType, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteCustomerAddress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'deleteProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'error' : IDL.Text, 'success' : IDL.Null })],
      [],
    ),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllOrders' : IDL.Func([], [IDL.Vec(OrderType)], ['query']),
  'getAllProductUpdates' : IDL.Func([], [IDL.Vec(ProductUpdate)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomerAddresses' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DeliveryAddress)],
      ['query'],
    ),
  'getCustomerOrders' : IDL.Func([IDL.Text], [IDL.Vec(OrderType)], ['query']),
  'getLogo' : IDL.Func([], [IDL.Opt(Logo)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProductUpdatesByProduct' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductUpdate)],
      ['query'],
    ),
  'getProductUpdatesByType' : IDL.Func(
      [ProductUpdateType],
      [IDL.Vec(ProductUpdate)],
      ['query'],
    ),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getStoreSettings' : IDL.Func([], [StoreSettings], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdminSessionValid' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCustomerSessionValid' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'loginCustomerByEmail' : IDL.Func([IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCustomerAddress' : IDL.Func([IDL.Text, DeliveryAddress], [], []),
  'setLogo' : IDL.Func([Logo], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [UpdateProductPayload],
      [IDL.Variant({ 'error' : IDL.Text, 'success' : Product })],
      [],
    ),
  'updateStoreSettings' : IDL.Func([StoreSettings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Price = IDL.Record({
    'salePrice' : IDL.Opt(IDL.Float64),
    'listPrice' : IDL.Float64,
  });
  const FlavorVariant = IDL.Record({
    'weight' : IDL.Nat,
    'flavor' : IDL.Text,
    'description' : IDL.Text,
    'price' : Price,
  });
  const WeightVariant = IDL.Record({
    'weight' : IDL.Nat,
    'description' : IDL.Text,
    'price' : Price,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'flavorVariant' : IDL.Opt(FlavorVariant),
    'quantity' : IDL.Nat,
    'weightVariant' : IDL.Opt(WeightVariant),
  });
  const DeliveryAddress = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const ProductVariants = IDL.Variant({
    'weight' : IDL.Vec(WeightVariant),
    'flavor' : IDL.Vec(FlavorVariant),
  });
  const AvailabilityStatus = IDL.Variant({
    'inStock' : IDL.Null,
    'outOfStock' : IDL.Null,
    'limited' : IDL.Null,
  });
  const Category = IDL.Variant({
    'beeProducts' : IDL.Null,
    'rawHoney' : IDL.Null,
    'naturalHoney' : IDL.Null,
  });
  const CreateProductPayload = IDL.Record({
    'name' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Opt(ProductVariants),
    'availability' : AvailabilityStatus,
    'stock' : IDL.Nat,
    'category' : Category,
    'image' : IDL.Text,
    'price' : Price,
  });
  const Time = IDL.Int;
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'created' : Time,
    'isDeleted' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Opt(ProductVariants),
    'availability' : AvailabilityStatus,
    'stock' : IDL.Nat,
    'timestamp' : Time,
    'category' : Category,
    'image' : IDL.Text,
    'price' : Price,
  });
  const ProductUpdateType = IDL.Variant({
    'seasonalAvailability' : IDL.Null,
    'priceUpdate' : IDL.Null,
    'newHarvest' : IDL.Null,
    'limitedTimeOffer' : IDL.Null,
  });
  const ContactFormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'transit' : IDL.Null,
    'delivered' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const CustomerIdentifier = IDL.Variant({
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderType = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'customerIdentifier' : CustomerIdentifier,
    'createdAt' : Time,
    'updatedAt' : Time,
    'address' : DeliveryAddress,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Float64,
  });
  const ProductUpdate = IDL.Record({
    'id' : IDL.Nat,
    'productUpdateType' : ProductUpdateType,
    'productId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Logo = IDL.Record({
    'data' : IDL.Vec(IDL.Nat8),
    'mimeType' : IDL.Text,
  });
  const StoreSettings = IDL.Record({
    'certificationsContent' : IDL.Text,
    'backgroundImage' : IDL.Opt(IDL.Text),
    'mapUrl' : IDL.Text,
    'aboutContent' : IDL.Text,
    'certificationsImage' : IDL.Opt(IDL.Text),
    'contactDetails' : IDL.Text,
  });
  const UpdateProductPayload = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'variants' : IDL.Opt(ProductVariants),
    'availability' : AvailabilityStatus,
    'stock' : IDL.Nat,
    'category' : Category,
    'image' : IDL.Text,
    'price' : Price,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminLogin' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'error' : IDL.Text, 'success' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrder' : IDL.Func(
        [IDL.Text, IDL.Vec(OrderItem), IDL.Float64, DeliveryAddress],
        [IDL.Variant({ 'success' : IDL.Nat })],
        [],
      ),
    'createProduct' : IDL.Func(
        [CreateProductPayload],
        [IDL.Variant({ 'error' : IDL.Text, 'success' : Product })],
        [],
      ),
    'createProductUpdate' : IDL.Func(
        [ProductUpdateType, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteCustomerAddress' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'deleteProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'error' : IDL.Text, 'success' : IDL.Null })],
        [],
      ),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllOrders' : IDL.Func([], [IDL.Vec(OrderType)], ['query']),
    'getAllProductUpdates' : IDL.Func([], [IDL.Vec(ProductUpdate)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomerAddresses' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DeliveryAddress)],
        ['query'],
      ),
    'getCustomerOrders' : IDL.Func([IDL.Text], [IDL.Vec(OrderType)], ['query']),
    'getLogo' : IDL.Func([], [IDL.Opt(Logo)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProductUpdatesByProduct' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductUpdate)],
        ['query'],
      ),
    'getProductUpdatesByType' : IDL.Func(
        [ProductUpdateType],
        [IDL.Vec(ProductUpdate)],
        ['query'],
      ),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getStoreSettings' : IDL.Func([], [StoreSettings], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdminSessionValid' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCustomerSessionValid' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'loginCustomerByEmail' : IDL.Func([IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCustomerAddress' : IDL.Func([IDL.Text, DeliveryAddress], [], []),
    'setLogo' : IDL.Func([Logo], [], []),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [UpdateProductPayload],
        [IDL.Variant({ 'error' : IDL.Text, 'success' : Product })],
        [],
      ),
    'updateStoreSettings' : IDL.Func([StoreSettings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };