/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface FlavorVariant {
    weight: bigint;
    flavor: string;
    description: string;
    price: Price;
}
export type Time = bigint;
export interface WeightVariant {
    weight: bigint;
    description: string;
    price: Price;
}
export interface ProductUpdate {
    id: bigint;
    productUpdateType: ProductUpdateType;
    productId: bigint;
    message: string;
    timestamp: Time;
}
export interface Price {
    salePrice?: number;
    listPrice: number;
}
export type ProductVariants = {
    __kind__: "weight";
    weight: Array<WeightVariant>;
} | {
    __kind__: "flavor";
    flavor: Array<FlavorVariant>;
};
export interface ContactFormSubmission {
    id: bigint;
    name: string;
    email: string;
    message: string;
    timestamp: Time;
}
export interface Logo {
    data: Uint8Array;
    mimeType: string;
}
export interface Product {
    id: bigint;
    created: Time;
    isDeleted: boolean;
    name: string;
    description: string;
    variants?: ProductVariants;
    availability: AvailabilityStatus;
    stock: bigint;
    timestamp: Time;
    category: Category;
    image: string;
    price: Price;
}
export type SeedProductsResult = {
    __kind__: "seeded";
    seeded: {
        count: bigint;
    };
} | {
    __kind__: "alreadySeeded";
    alreadySeeded: null;
};
export enum AvailabilityStatus {
    inStock = "inStock",
    outOfStock = "outOfStock",
    limited = "limited"
}
export enum Category {
    beeProducts = "beeProducts",
    rawHoney = "rawHoney",
    naturalHoney = "naturalHoney"
}
export enum ProductUpdateType {
    seasonalAvailability = "seasonalAvailability",
    priceUpdate = "priceUpdate",
    newHarvest = "newHarvest",
    limitedTimeOffer = "limitedTimeOffer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addAdmin(_newAdmin: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createProduct(name: string, description: string, category: Category, price: Price, image: string, availability: AvailabilityStatus, variants: ProductVariants | null, stock: bigint): Promise<bigint>;
    createProductUpdate(productUpdateType: ProductUpdateType, productId: bigint, message: string): Promise<bigint>;
    deleteProduct(id: bigint): Promise<void>;
    deleteProductUpdate(id: bigint): Promise<void>;
    getAllProductUpdates(): Promise<Array<ProductUpdate>>;
    getAllProducts(): Promise<Array<Product>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactFormSubmissions(): Promise<Array<ContactFormSubmission>>;
    getLimitedProducts(): Promise<Array<Product>>;
    getLogo(): Promise<Logo | null>;
    getProduct(id: bigint): Promise<Product | null>;
    getProductUpdatesByProduct(productId: bigint): Promise<Array<ProductUpdate>>;
    getProductUpdatesByType(productUpdateType: ProductUpdateType): Promise<Array<ProductUpdate>>;
    getProductsByCategory(category: Category): Promise<Array<Product>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAdmins(): Promise<Array<Principal>>;
    removeAdmin(_adminToRemove: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    seedProducts(): Promise<SeedProductsResult>;
    submitContactForm(name: string, email: string, message: string): Promise<bigint>;
    updateLogo(mimeType: string, data: Uint8Array): Promise<void>;
    updateProduct(id: bigint, name: string, description: string, category: Category, price: Price, image: string, availability: AvailabilityStatus, variants: ProductVariants | null, stock: bigint): Promise<void>;
}
import type { AvailabilityStatus as _AvailabilityStatus, Category as _Category, FlavorVariant as _FlavorVariant, Logo as _Logo, Price as _Price, Product as _Product, ProductUpdate as _ProductUpdate, ProductUpdateType as _ProductUpdateType, ProductVariants as _ProductVariants, SeedProductsResult as _SeedProductsResult, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, WeightVariant as _WeightVariant } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createProduct(arg0: string, arg1: string, arg2: Category, arg3: Price, arg4: string, arg5: AvailabilityStatus, arg6: ProductVariants | null, arg7: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, arg1, to_candid_Category_n3(this._uploadFile, this._downloadFile, arg2), to_candid_Price_n5(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_AvailabilityStatus_n7(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6), arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, arg1, to_candid_Category_n3(this._uploadFile, this._downloadFile, arg2), to_candid_Price_n5(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_AvailabilityStatus_n7(this._uploadFile, this._downloadFile, arg5), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg6), arg7);
            return result;
        }
    }
    async createProductUpdate(arg0: ProductUpdateType, arg1: bigint, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createProductUpdate(to_candid_ProductUpdateType_n18(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProductUpdate(to_candid_ProductUpdateType_n18(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteProductUpdate(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProductUpdate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProductUpdate(arg0);
            return result;
        }
    }
    async getAllProductUpdates(): Promise<Array<ProductUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductUpdates();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductUpdates();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactFormSubmissions(): Promise<Array<ContactFormSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactFormSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactFormSubmissions();
            return result;
        }
    }
    async getLimitedProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLimitedProducts();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLimitedProducts();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLogo(): Promise<Logo | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLogo();
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLogo();
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: bigint): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductUpdatesByProduct(arg0: bigint): Promise<Array<ProductUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductUpdatesByProduct(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductUpdatesByProduct(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductUpdatesByType(arg0: ProductUpdateType): Promise<Array<ProductUpdate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductUpdatesByType(to_candid_ProductUpdateType_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductUpdatesByType(to_candid_ProductUpdateType_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductsByCategory(arg0: Category): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByCategory(to_candid_Category_n3(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAdmins(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAdmins();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAdmins();
            return result;
        }
    }
    async removeAdmin(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async seedProducts(): Promise<SeedProductsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.seedProducts();
                return from_candid_SeedProductsResult_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.seedProducts();
            return from_candid_SeedProductsResult_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2);
            return result;
        }
    }
    async updateLogo(arg0: string, arg1: Uint8Array): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLogo(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLogo(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: string, arg3: Category, arg4: Price, arg5: string, arg6: AvailabilityStatus, arg7: ProductVariants | null, arg8: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, to_candid_Category_n3(this._uploadFile, this._downloadFile, arg3), to_candid_Price_n5(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_AvailabilityStatus_n7(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg7), arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, to_candid_Category_n3(this._uploadFile, this._downloadFile, arg3), to_candid_Price_n5(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_AvailabilityStatus_n7(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg7), arg8);
            return result;
        }
    }
}
function from_candid_AvailabilityStatus_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AvailabilityStatus): AvailabilityStatus {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Category_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Category): Category {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
function from_candid_FlavorVariant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlavorVariant): FlavorVariant {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Price_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Price): Price {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_ProductUpdateType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductUpdateType): ProductUpdateType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_ProductUpdate_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductUpdate): ProductUpdate {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_ProductVariants_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductVariants): ProductVariants {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_SeedProductsResult_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeedProductsResult): SeedProductsResult {
    return from_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_WeightVariant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WeightVariant): WeightVariant {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductVariants]): ProductVariants | null {
    return value.length === 0 ? null : from_candid_ProductVariants_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Logo]): Logo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    productUpdateType: _ProductUpdateType;
    productId: bigint;
    message: string;
    timestamp: _Time;
}): {
    id: bigint;
    productUpdateType: ProductUpdateType;
    productId: bigint;
    message: string;
    timestamp: Time;
} {
    return {
        id: value.id,
        productUpdateType: from_candid_ProductUpdateType_n23(_uploadFile, _downloadFile, value.productUpdateType),
        productId: value.productId,
        message: value.message,
        timestamp: value.timestamp
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    created: _Time;
    isDeleted: boolean;
    name: string;
    description: string;
    variants: [] | [_ProductVariants];
    availability: _AvailabilityStatus;
    stock: bigint;
    timestamp: _Time;
    category: _Category;
    image: string;
    price: _Price;
}): {
    id: bigint;
    created: Time;
    isDeleted: boolean;
    name: string;
    description: string;
    variants?: ProductVariants;
    availability: AvailabilityStatus;
    stock: bigint;
    timestamp: Time;
    category: Category;
    image: string;
    price: Price;
} {
    return {
        id: value.id,
        created: value.created,
        isDeleted: value.isDeleted,
        name: value.name,
        description: value.description,
        variants: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.variants)),
        availability: from_candid_AvailabilityStatus_n40(_uploadFile, _downloadFile, value.availability),
        stock: value.stock,
        timestamp: value.timestamp,
        category: from_candid_Category_n42(_uploadFile, _downloadFile, value.category),
        image: value.image,
        price: from_candid_Price_n34(_uploadFile, _downloadFile, value.price)
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: bigint;
    description: string;
    price: _Price;
}): {
    weight: bigint;
    description: string;
    price: Price;
} {
    return {
        weight: value.weight,
        description: value.description,
        price: from_candid_Price_n34(_uploadFile, _downloadFile, value.price)
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salePrice: [] | [number];
    listPrice: number;
}): {
    salePrice?: number;
    listPrice: number;
} {
    return {
        salePrice: record_opt_to_undefined(from_candid_opt_n36(_uploadFile, _downloadFile, value.salePrice)),
        listPrice: value.listPrice
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: bigint;
    flavor: string;
    description: string;
    price: _Price;
}): {
    weight: bigint;
    flavor: string;
    description: string;
    price: Price;
} {
    return {
        weight: value.weight,
        flavor: value.flavor,
        description: value.description,
        price: from_candid_Price_n34(_uploadFile, _downloadFile, value.price)
    };
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    seasonalAvailability: null;
} | {
    priceUpdate: null;
} | {
    newHarvest: null;
} | {
    limitedTimeOffer: null;
}): ProductUpdateType {
    return "seasonalAvailability" in value ? ProductUpdateType.seasonalAvailability : "priceUpdate" in value ? ProductUpdateType.priceUpdate : "newHarvest" in value ? ProductUpdateType.newHarvest : "limitedTimeOffer" in value ? ProductUpdateType.limitedTimeOffer : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: Array<_WeightVariant>;
} | {
    flavor: Array<_FlavorVariant>;
}): {
    __kind__: "weight";
    weight: Array<WeightVariant>;
} | {
    __kind__: "flavor";
    flavor: Array<FlavorVariant>;
} {
    return "weight" in value ? {
        __kind__: "weight",
        weight: from_candid_vec_n31(_uploadFile, _downloadFile, value.weight)
    } : "flavor" in value ? {
        __kind__: "flavor",
        flavor: from_candid_vec_n37(_uploadFile, _downloadFile, value.flavor)
    } : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    inStock: null;
} | {
    outOfStock: null;
} | {
    limited: null;
}): AvailabilityStatus {
    return "inStock" in value ? AvailabilityStatus.inStock : "outOfStock" in value ? AvailabilityStatus.outOfStock : "limited" in value ? AvailabilityStatus.limited : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    beeProducts: null;
} | {
    rawHoney: null;
} | {
    naturalHoney: null;
}): Category {
    return "beeProducts" in value ? Category.beeProducts : "rawHoney" in value ? Category.rawHoney : "naturalHoney" in value ? Category.naturalHoney : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    seeded: {
        count: bigint;
    };
} | {
    alreadySeeded: null;
}): {
    __kind__: "seeded";
    seeded: {
        count: bigint;
    };
} | {
    __kind__: "alreadySeeded";
    alreadySeeded: null;
} {
    return "seeded" in value ? {
        __kind__: "seeded",
        seeded: value.seeded
    } : "alreadySeeded" in value ? {
        __kind__: "alreadySeeded",
        alreadySeeded: value.alreadySeeded
    } : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ProductUpdate>): Array<ProductUpdate> {
    return value.map((x)=>from_candid_ProductUpdate_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WeightVariant>): Array<WeightVariant> {
    return value.map((x)=>from_candid_WeightVariant_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FlavorVariant>): Array<FlavorVariant> {
    return value.map((x)=>from_candid_FlavorVariant_n38(_uploadFile, _downloadFile, x));
}
function to_candid_AvailabilityStatus_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): _AvailabilityStatus {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_Category_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): _Category {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FlavorVariant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlavorVariant): _FlavorVariant {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_Price_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Price): _Price {
    return to_candid_record_n6(_uploadFile, _downloadFile, value);
}
function to_candid_ProductUpdateType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductUpdateType): _ProductUpdateType {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_ProductVariants_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductVariants): _ProductVariants {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_WeightVariant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WeightVariant): _WeightVariant {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductVariants | null): [] | [_ProductVariants] {
    return value === null ? candid_none() : candid_some(to_candid_ProductVariants_n10(_uploadFile, _downloadFile, value));
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: bigint;
    flavor: string;
    description: string;
    price: Price;
}): {
    weight: bigint;
    flavor: string;
    description: string;
    price: _Price;
} {
    return {
        weight: value.weight,
        flavor: value.flavor,
        description: value.description,
        price: to_candid_Price_n5(_uploadFile, _downloadFile, value.price)
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    weight: bigint;
    description: string;
    price: Price;
}): {
    weight: bigint;
    description: string;
    price: _Price;
} {
    return {
        weight: value.weight,
        description: value.description,
        price: to_candid_Price_n5(_uploadFile, _downloadFile, value.price)
    };
}
function to_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    salePrice?: number;
    listPrice: number;
}): {
    salePrice: [] | [number];
    listPrice: number;
} {
    return {
        salePrice: value.salePrice ? candid_some(value.salePrice) : candid_none(),
        listPrice: value.listPrice
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "weight";
    weight: Array<WeightVariant>;
} | {
    __kind__: "flavor";
    flavor: Array<FlavorVariant>;
}): {
    weight: Array<_WeightVariant>;
} | {
    flavor: Array<_FlavorVariant>;
} {
    return value.__kind__ === "weight" ? {
        weight: to_candid_vec_n15(_uploadFile, _downloadFile, value.weight)
    } : value.__kind__ === "flavor" ? {
        flavor: to_candid_vec_n12(_uploadFile, _downloadFile, value.flavor)
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductUpdateType): {
    seasonalAvailability: null;
} | {
    priceUpdate: null;
} | {
    newHarvest: null;
} | {
    limitedTimeOffer: null;
} {
    return value == ProductUpdateType.seasonalAvailability ? {
        seasonalAvailability: null
    } : value == ProductUpdateType.priceUpdate ? {
        priceUpdate: null
    } : value == ProductUpdateType.newHarvest ? {
        newHarvest: null
    } : value == ProductUpdateType.limitedTimeOffer ? {
        limitedTimeOffer: null
    } : value;
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Category): {
    beeProducts: null;
} | {
    rawHoney: null;
} | {
    naturalHoney: null;
} {
    return value == Category.beeProducts ? {
        beeProducts: null
    } : value == Category.rawHoney ? {
        rawHoney: null
    } : value == Category.naturalHoney ? {
        naturalHoney: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AvailabilityStatus): {
    inStock: null;
} | {
    outOfStock: null;
} | {
    limited: null;
} {
    return value == AvailabilityStatus.inStock ? {
        inStock: null
    } : value == AvailabilityStatus.outOfStock ? {
        outOfStock: null
    } : value == AvailabilityStatus.limited ? {
        limited: null
    } : value;
}
function to_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FlavorVariant>): Array<_FlavorVariant> {
    return value.map((x)=>to_candid_FlavorVariant_n13(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<WeightVariant>): Array<_WeightVariant> {
    return value.map((x)=>to_candid_WeightVariant_n16(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
